"""adding junction table between seekers and jobs to record applications

Revision ID: 0309218d489c
Revises: 
Create Date: 2021-12-31 21:20:49.149296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0309218d489c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiters_id'), 'recruiters', ['id'], unique=False)
    op.create_table('seekers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('resume', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('portfolio', sa.String(), nullable=True),
    sa.Column('job_feild', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seekers_id'), 'seekers', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('Posted_by', sa.Integer(), nullable=False),
    sa.Column('post_time', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('eligibility_criteria', sa.String(), nullable=False),
    sa.Column('job_location', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Posted_by'], ['recruiters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('jobs_applied',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seeker_id'], ['seekers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_applied_id'), 'jobs_applied', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_applied_id'), table_name='jobs_applied')
    op.drop_table('jobs_applied')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_seekers_id'), table_name='seekers')
    op.drop_table('seekers')
    op.drop_index(op.f('ix_recruiters_id'), table_name='recruiters')
    op.drop_table('recruiters')
    # ### end Alembic commands ###
