"""adding relationship between recruiter and jobs and primary key jobs applied

Revision ID: 5459702635f4
Revises: 0309218d489c
Create Date: 2022-01-03 00:18:16.494143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5459702635f4'
down_revision = '0309218d489c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
