"""changed spelling of posted_by removed not null from posted by

Revision ID: 7256de95747c
Revises: 5459702635f4
Create Date: 2022-01-10 01:04:59.639496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7256de95747c'
down_revision = '5459702635f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('posted_by', sa.Integer(), nullable=True))
    op.drop_constraint('jobs_Posted_by_fkey', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'recruiters', ['posted_by'], ['id'], ondelete='CASCADE')
    op.drop_column('jobs', 'Posted_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('Posted_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_Posted_by_fkey', 'jobs', 'recruiters', ['Posted_by'], ['id'], ondelete='CASCADE')
    op.drop_column('jobs', 'posted_by')
    # ### end Alembic commands ###
