"""Added a taable for recording Selected Candidates

Revision ID: ce2c476c0fcf
Revises: 7256de95747c
Create Date: 2022-01-23 21:22:31.119849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2c476c0fcf'
down_revision = '7256de95747c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
